"""Download the three web fonts into public/fonts/ and write src/styles/fonts.css.

The site used to pull Amiri, Tajawal and Lora from fonts.googleapis.com with a
render-blocking <link> in every page head. Three families, ten faces, on the
critical path of all 74 pages, with Amiri carrying every heading.

This fetches the woff2 files once so they are served from our own origin. Only
the subsets the site can actually show are kept: Arabic and Latin. Google also
serves Cyrillic, Greek, Vietnamese and math subsets for these families, and the
site has no route that renders them.

The @font-face rules are written into src/styles/fonts.css, NOT into public/,
because global.css @imports them: bundled with the rest of the CSS they cost no
extra request, where a <link> to /fonts/fonts.css was a second blocking hop on
the critical path of every page. The woff2 files stay in public/ - their URLs are
absolute, so Vite leaves them alone.

The url() carries the site's BASE path (/harat-al-aqur on GitHub Pages). Vite does
not rewrite a `/`-absolute url() to include the base, and a public asset under a
base is served at <base>/fonts/..., not /fonts/... - so a bare /fonts/ 404s on the
deployed site and every face falls back. If the site ever moves to a domain root,
set BASE to "".

The url() is rewritten WITHOUT re-stating format(): Google's block already ends
in `format('woff2')`, and a second one makes the whole src descriptor invalid, so
every face is silently dropped and the page falls back to Times New Roman. That
shipped once. Do not reintroduce it.

Re-run only to pick up upstream font revisions. Both outputs are generated.
"""
import re
import pathlib
import urllib.request

OUT = pathlib.Path("public/fonts")
CSS = pathlib.Path("src/styles/fonts.css")
# The `base` from astro.config.mjs. Prefixes each url() so the fonts resolve on
# the deployed site. Empty string if the site is ever served from a domain root.
BASE = "/harat-al-aqur"
# A modern UA is required, or Google serves ttf instead of woff2.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0 Safari/537.36")

FAMILIES = {
    "Amiri":   ("Amiri:ital,wght@0,400;0,700;1,400",   {"arabic", "latin", "latin-ext"}),
    "Tajawal": ("Tajawal:wght@300;400;500;700",         {"arabic", "latin"}),
    "Lora":    ("Lora:ital,wght@0,400;0,600;1,400",     {"latin", "latin-ext"}),
}


def get(url: str) -> bytes:
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA}), timeout=60
    ).read()


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    blocks, kept, skipped = [], 0, 0

    for family, (spec, subsets) in FAMILIES.items():
        css = get(f"https://fonts.googleapis.com/css2?family={spec}&display=swap").decode()
        # Google emits "/* subset */" immediately before each @font-face block.
        for subset, block in re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css):
            if subset not in subsets:
                skipped += 1
                continue
            url = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            if not url:
                skipped += 1
                continue
            weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
            italic = "italic" in re.search(r"font-style:\s*(\w+)", block).group(1)
            name = f"{family.lower()}-{subset}-{weight}{'-italic' if italic else ''}.woff2"
            (OUT / name).write_bytes(get(url.group(1)))
            blocks.append(block.replace(url.group(0), f"url({BASE}/fonts/{name})"))
            kept += 1
            print(f"  {name}")

    header = (
        "/* Generated by work/fetch_fonts.py - do not hand-edit.\n"
        "   Self-hosted so the fonts are not a render-blocking third-party request.\n"
        "   Arabic and Latin subsets only. @import-ed by global.css, so these\n"
        "   rules ride in the page stylesheet instead of a second request. */\n\n"
    )
    CSS.write_text(header + "\n\n".join(blocks) + "\n", encoding="utf-8")
    total = sum(f.stat().st_size for f in OUT.glob("*.woff2"))
    print(f"\n{kept} faces kept, {skipped} subsets skipped, {total/1024:.0f} KB total")


if __name__ == "__main__":
    main()
