import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// The sections live outside src/ on purpose: content/ is generated by
// work/build_content.py and is the same tree the extraction scripts write to.
// One collection per language, paired by `slug` so the language toggle can map
// page-to-page instead of dropping the visitor on the homepage.
const section = z.object({
  slug: z.string(),
  lang: z.enum(['ar', 'en']),
  title: z.string(),
  order: z.number()
});

// The book's closing pages: the author's acknowledgements and his afterword.
// Arabic only - the printed book has no English edition, so the translation
// lives in src/lib/credits.ts instead.
const backMatter = z.object({
  slug: z.string(),
  lang: z.literal('ar'),
  title: z.string()
});

export const collections = {
  ar: defineCollection({
    loader: glob({ pattern: '**/*.md', base: './content/ar/sections' }),
    schema: section
  }),
  en: defineCollection({
    loader: glob({ pattern: '**/*.md', base: './content/en/sections' }),
    schema: section
  }),
  backMatter: defineCollection({
    loader: glob({ pattern: '**/*.md', base: './content/ar/back-matter' }),
    schema: backMatter
  })
};
